version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create test results folder
          command: |
            mkdir ~/repo/reports
            mkdir ~/repo/reports/junit
      - add_ssh_keys:
          fingerprints:
            - "71:0c:eb:65:06:fe:fe:67:4c:f6:ae:a8:cf:0e:78:04"
      - run:
          name: Git config
          command: |
            echo $GIT_EMAIL
            echo $GIT_USERNAME
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_USERNAME
      - run:
          name: Config yarn for deploy
          command: |
            yarn config set _authToken $YARN_TOKEN
            echo "//registry.yarnpkg.com/:_authToken=$YARN_TOKEN" >>~/.npmrc
      - run:
          name: Make git hook executable
          command: |
            chmod +x ~/repo/.git/hooks/*
      - run:
          name: Install all dependenciees
          command: yarn install
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: ~/repo/reports
      - store_artifacts:
          path: ~/repo/reports
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn version --patch
              yarn publish
              git push --follow-tags
            fi

workflows:
  version: 2
  build:
    jobs:
      - test
