version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create test results folder
          command: |
            mkdir ~/repo/reports
            mkdir ~/repo/reports/junit
      - run:
          name: Install all dependenciees
          command: yarn install
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test-ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: ~/repo/reports
      - store_artifacts:
          path: ~/repo/reports
      - run:
          command: yarn version --patch && yarn publish
workflows:
  version: 2
  build:
    jobs:
      - test
